name: Auto-build doxygen docs
on:
  push:
    branches:
      - master
      #! only for test, remove before MR !
      - doxygen
      - automr
  
jobs:  
  doxygen:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        show-progress: ''
    - name: Setup and run doxygen
      run: sudo apt install doxygen graphviz qhelpgenerator-qt5 -y
    - name: Run doxygen
      run: doxygen Doxyfile
    - uses: actions/upload-artifact@v4
      with:
        name: qch-artifact
        path: ${{ github.workspace }}/doc/QElectroTech.qch 
    - uses: actions/upload-pages-artifact@v3
      with: 
       path: ${{ github.workspace }}/doc/html/
    
  sync:
    needs: doxygen
    runs-on: ubuntu-latest
    permissions:
       contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: qch-artifact
          path: ${{ github.workspace }}
      - run: ls -R
      - run: git status
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          show-progress: ''      
      -  run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "generated"
          git push              
  deploy:
    # Add a dependency to the build job
    needs: doxygen

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
