name: Update QCH file
on:
  push:
    branches:
      - master
      - automr

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          show-progress: ''
      - uses: actions/download-artifact@v4
        with:
          name: qch-artifact    